// NOTE: need a Coordinator and several workers. 
use futures::prelude::*;
use tarpc::{
    client, context,
    server::{self, Channel},
};

// This is the service definition. It looks a lot like a trait definition.
// It defines one RPC, hello, which takes one arg, name, and returns a String.
#[tarpc::service]
trait Worker {
    /// Returns a greeting for name.
    async fn hello(name: String) -> String;

    async fn bye(name: String) -> String;
}

#[derive(Clone)]
struct HelloServer;

impl Worker for HelloServer {
    async fn hello(self, _: context::Context, name: String) -> String {
        format!("Hello, {name}!")
    }

    async fn bye(self, _: context::Context, name: String) -> String {
        format!("Bye, {name}!")
    }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let (client_transport, server_transport) = tarpc::transport::channel::unbounded();

    let server = server::BaseChannel::with_defaults(server_transport);
    tokio::spawn(
        server.execute(HelloServer.serve())
            // Handle all requests concurrently.
            .for_each(|response| async move {
                tokio::spawn(response);
            }));

    // WorkerClient is generated by the #[tarpc::service] attribute. It has a constructor `new`
    // that takes a config and any Transport as input.
    let mut client: WorkerClient = WorkerClient::new(client::Config::default(), client_transport).spawn();

    // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // args as defined, with the addition of a Context, which is always the first arg. The Context
    // specifies a deadline and trace information which can be helpful in debugging requests.
    let hello: String = client.hello(context::current(), "Fucker".to_string()).await?;
    let bye: String = client.bye(context::current(), "Fucker".to_string()).await?;

    println!("{hello}");

    Ok(())
}

// Modules
pub mod ds;
pub mod rpc;
pub mod coordinator;
